"use client";

import React, { useState, useEffect } from 'react';
import { useRouter, usePathname } from 'next/navigation';
import { Sandpack } from "@codesandbox/sandpack-react";
import { Globe, Cpu, Bot, FolderClosed, BookOpen, Sparkles, Zap, Image as ImageIcon, Plus, CheckSquare, Search, FlaskConical, MessageSquare, Library } from 'lucide-react';
import { createAvatar } from '@dicebear/core';
import * as notionists from '@dicebear/notionists';

const amyAvatar = createAvatar(notionists, { seed: 'Jocelyn', backgroundColor: ['transparent'], scale: 120 }).toDataUri();
const kaiAvatar = createAvatar(notionists, { seed: 'Felix', backgroundColor: ['transparent'], scale: 120 }).toDataUri();

type Theme = { bg: string, text: string, border: string };
type ServerType = { id: string, icon: string, tooltip: string, theme: Theme };
type Tab = { id: string, label: string, href: string };

const PREDEFINED_THEMES = [
  { name: 'Slate', bg: '#f1f5f9', text: '#334155', border: '#94a3b8' },
  { name: 'Blue', bg: '#eff6ff', text: '#2563eb', border: '#1d4ed8' },
  { name: 'Fuchsia', bg: '#fdf4ff', text: '#c026d3', border: '#a21caf' },
  { name: 'Emerald', bg: '#ecfdf5', text: '#059669', border: '#047857' },
  { name: 'Amber', bg: '#fffbeb', text: '#d97706', border: '#b45309' },
  { name: 'Rose', bg: '#fff1f2', text: '#e11d48', border: '#be123c' },
];

const MOCK_GENERATED_CODE = `import React from 'react';

export default function App() {
  return (
    <div style={{ padding: '24px', fontFamily: 'sans-serif', background: '#ffffff', minHeight: '100vh' }}>
      <h1 style={{ fontSize: '24px', fontWeight: 'bold', color: '#0f172a', margin: 0 }}>Stripe MRR Velocity</h1>
      <p style={{ color: '#64748b', fontSize: '14px', marginTop: '4px' }}>Real-time dashboard generated by Amy</p>
      
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px', marginTop: '24px' }}>
        
        <div style={{ padding: '20px', background: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
          <p style={{ margin: 0, fontSize: '12px', color: '#64748b', fontWeight: 600, textTransform: 'uppercase' }}>Current MRR</p>
          <p style={{ margin: '8px 0 0 0', fontSize: '32px', fontWeight: 'bold', color: '#0f172a' }}>$42,500</p>
          <p style={{ margin: '4px 0 0 0', fontSize: '12px', color: '#059669', fontWeight: 600 }}>+12% from last month</p>
        </div>

        <div style={{ padding: '20px', background: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
          <p style={{ margin: 0, fontSize: '12px', color: '#64748b', fontWeight: 600, textTransform: 'uppercase' }}>Active Subs</p>
          <p style={{ margin: '8px 0 0 0', fontSize: '32px', fontWeight: 'bold', color: '#0f172a' }}>1,204</p>
          <p style={{ margin: '4px 0 0 0', fontSize: '12px', color: '#059669', fontWeight: 600 }}>+45 new this week</p>
        </div>

        <div style={{ padding: '20px', background: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
          <p style={{ margin: 0, fontSize: '12px', color: '#64748b', fontWeight: 600, textTransform: 'uppercase' }}>Churn Rate</p>
          <p style={{ margin: '8px 0 0 0', fontSize: '32px', fontWeight: 'bold', color: '#0f172a' }}>1.2%</p>
          <p style={{ margin: '4px 0 0 0', fontSize: '12px', color: '#e11d48', fontWeight: 600 }}>-0.4% improvement</p>
        </div>

      </div>

      <div style={{ marginTop: '24px', padding: '20px', background: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0', height: '300px', display: 'flex', flexDirection: 'column' }}>
        <p style={{ margin: 0, fontSize: '14px', color: '#0f172a', fontWeight: 600, marginBottom: '20px' }}>MRR Growth Trajectory</p>
        <div style={{ flex: 1, display: 'flex', alignItems: 'flex-end', gap: '8px' }}>
          {/* Mock Bar Chart */}
          {[40, 55, 45, 70, 85, 60, 95].map((h, i) => (
            <div key={i} style={{ flex: 1, background: '#6366f1', height: \`\${h}%\`, borderRadius: '4px 4px 0 0', opacity: 0.8 + (i * 0.05) }} />
          ))}
        </div>
      </div>
    </div>
  );
}
`;

export default function AppShell({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  const pathname = usePathname();

  const [activeServerId, setActiveServerId] = useState<string>('GLOBAL');
  const [servers, setServers] = useState<ServerType[]>([]);
  
  const [tabs, setTabs] = useState<Tab[]>([{ id: 'tab-home', label: 'Harness Overview', href: '/' }]);
  const [activeTabHref, setActiveTabHref] = useState<string>('/');

  const [activePane, setActivePane] = useState<'NONE' | 'AMY' | 'KAI'>('NONE');
  
  // Artifact Canvas State
  const [artifactMode, setArtifactMode] = useState<'PAGE' | 'SANDBOX' | 'IFRAME'>('PAGE');
  const [amyChatInput, setAmyChatInput] = useState('');

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [newProjectName, setNewProjectName] = useState('');
  const [newProjectInitials, setNewProjectInitials] = useState('');
  const [selectedTheme, setSelectedTheme] = useState<Theme>(PREDEFINED_THEMES[3]);
  const [openSections, setOpenSections] = useState<Record<string, boolean>>({
    GlobalDashboard: true, CoreEngines: true, AgentCommand: true, ProjectTasks: true, ProjectWiki: true
  });

  useEffect(() => {
    fetch('/api/projects').then(res => res.json()).then(data => setServers(data)).catch(err => console.error(err));
  }, []);

  useEffect(() => { 
    if (pathname.startsWith('/projects/')) {
      const id = pathname.split('/')[2];
      if (id) setActiveServerId(id);
    } else {
      setActiveServerId('GLOBAL');
    }
    if (artifactMode === 'PAGE') setActiveTabHref(pathname); 
  }, [pathname, artifactMode]);

  const toggleSection = (section: string) => setOpenSections(prev => ({ ...prev, [section]: !prev[section] }));

  const handleSidebarClick = (e: React.MouseEvent, href: string, label: string) => {
    e.preventDefault();
    setArtifactMode('PAGE');
    const existingTab = tabs.find(t => t.href === href);
    if (!existingTab) setTabs([...tabs, { id: `tab-${Date.now()}`, label, href }]);
    setActiveTabHref(href);
    router.push(href);
  };

  const closeTab = (e: React.MouseEvent, href: string) => {
    e.stopPropagation();
    const newTabs = tabs.filter(t => t.href !== href);
    setTabs(newTabs);
    if (activeTabHref === href && newTabs.length > 0) {
      const fallbackHref = newTabs[newTabs.length - 1].href;
      setActiveTabHref(fallbackHref);
      router.push(fallbackHref);
    } else if (newTabs.length === 0) {
      setActiveTabHref('');
      router.push('/');
    }
  };

  const handleAmySubmit = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && amyChatInput.toLowerCase().includes('dashboard')) {
      setAmyChatInput('');
      
      // Spawn new artifact tab
      const artifactHref = '#artifact-mrr';
      setTabs([...tabs, { id: `tab-${Date.now()}`, label: '✨ MRR Dashboard', href: artifactHref }]);
      setActiveTabHref(artifactHref);
      setArtifactMode('SANDBOX');
    }
  };

  const getNavGroups = () => {
    if (activeServerId === 'GLOBAL') {
      return [
        { id: 'GlobalDashboard', title: 'Global Dashboard', icon: <Globe size={16} />, links: [ { href: '/', label: 'Harness Overview' }, { href: '/health', label: 'Janitor Health' } ] },
        { id: 'AgentCommand', title: 'Agent Command', icon: <Bot size={16} />, links: [ { href: '/agents', label: 'Agent Roster' }, { href: '/quarantine', label: 'Audit & Quarantine' } ] },
        { id: 'PersonalUse', title: 'Personal OS', icon: <Sparkles size={16} />, links: [ { href: '/routines', label: 'Routines Calendar' }, { href: '/calendar', label: 'Planning Calendar' }, { href: '/computer', label: 'Screen Control' }, { href: '/vault', label: 'Identity Vault' }, { href: '/preferences', label: 'Preferences' } ] },
        { id: 'CoreEngines', title: 'Core OS Engines', icon: <Cpu size={16} />, links: [ { href: '/tasks', label: 'Task Operations' }, { href: '/memory', label: 'Temporal Memory' }, { href: '/wiki', label: 'Knowledge Base' } ] }
      ];
    } else {
      return [
        { id: 'ProjectTasks', title: 'Project Operations', icon: <FolderClosed size={16} />, links: [ { href: `/projects/${activeServerId}/sprints`, label: 'Active Sprints' }, { href: `/projects/${activeServerId}/files`, label: 'Files & Assets' } ] },
        { id: 'ProjectWiki', title: 'Project Knowledge', icon: <BookOpen size={16} />, links: [ { href: `/projects/${activeServerId}/wiki`, label: 'Project Wiki' }, { href: `/projects/${activeServerId}/settings`, label: 'Project Settings' } ] }
      ];
    }
  };

  const navGroups = getNavGroups();

  return (
    <div className="app-container" style={{ display: 'flex', height: '100vh', overflow: 'hidden' }}>
      
      {isModalOpen && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(15, 23, 42, 0.4)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 }}>
          <div className="card" style={{ width: '400px', background: '#ffffff', padding: '32px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><h2 style={{ fontSize: '20px', margin: 0 }}>Create New Project</h2><button onClick={() => setIsModalOpen(false)} style={{ background: 'none', border: 'none', fontSize: '20px', cursor: 'pointer', color: '#64748b' }}>×</button></div>
            <div><label style={{ fontSize: '13px', fontWeight: 600, color: '#334155', display: 'block', marginBottom: '8px' }}>Project Name</label><input type="text" value={newProjectName} onChange={e => setNewProjectName(e.target.value)} placeholder="e.g. Marketing Site" style={{ width: '100%', padding: '10px 12px', borderRadius: '6px', border: '1px solid #cbd5e1', outline: 'none' }} /></div>
            <div><label style={{ fontSize: '13px', fontWeight: 600, color: '#334155', display: 'block', marginBottom: '8px' }}>Icon Initials (Max 2)</label><input type="text" maxLength={2} value={newProjectInitials} onChange={e => setNewProjectInitials(e.target.value.toUpperCase())} placeholder="MS" style={{ width: '100%', padding: '10px 12px', borderRadius: '6px', border: '1px solid #cbd5e1', outline: 'none' }} /></div>
            <div>
              <label style={{ fontSize: '13px', fontWeight: 600, color: '#334155', display: 'block', marginBottom: '8px' }}>Select Theme</label>
              <div style={{ display: 'flex', gap: '8px' }}>
                {PREDEFINED_THEMES.map((theme, i) => (
                  <button key={i} onClick={() => setSelectedTheme(theme)} style={{ width: '32px', height: '32px', borderRadius: '50%', cursor: 'pointer', background: theme.bg, border: `2px solid ${selectedTheme.bg === theme.bg ? theme.text : theme.border}`, boxShadow: selectedTheme.bg === theme.bg ? `0 0 0 2px ${theme.border}40` : 'none' }} title={theme.name} />
                ))}
              </div>
            </div>
            <button onClick={async () => { /* Add Project Logic simplified for brevity */ setIsModalOpen(false); }} className="btn" style={{ background: '#0f172a', color: 'white', padding: '12px', marginTop: '8px' }}>Create Project Environment</button>
          </div>
        </div>
      )}

      <div style={{ width: '68px', background: '#ffffff', borderRight: '1px solid #e2e8f0', display: 'flex', flexDirection: 'column', alignItems: 'center', paddingTop: '24px', gap: '16px', zIndex: 20, boxShadow: '2px 0 8px rgba(0,0,0,0.02)', flexShrink: 0 }}>
        <button onClick={() => { setActiveServerId('GLOBAL'); router.push('/'); }} style={{ width: '42px', height: '42px', borderRadius: '10px', background: activeServerId === 'GLOBAL' ? '#f1f5f9' : '#ffffff', color: activeServerId === 'GLOBAL' ? '#0f172a' : '#64748b', border: activeServerId === 'GLOBAL' ? '1px solid #cbd5e1' : '1px solid transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s ease' }} title="Global OS">
          <Globe size={20} />
        </button>
        <div style={{ width: '32px', height: '1px', background: '#e2e8f0', margin: '-4px 0' }}></div>
        {servers.map(server => {
          if (server.id === 'GLOBAL') return null;
          const isActive = activeServerId === server.id;
          return (
            <button key={server.id} onClick={() => { setActiveServerId(server.id); router.push(`/projects/${server.id}`); }} style={{ width: '42px', height: '42px', borderRadius: '10px', background: isActive ? server.theme.bg : '#ffffff', color: isActive ? server.theme.text : '#64748b', fontSize: '14px', fontWeight: 700, letterSpacing: '0.5px', border: isActive ? `1px solid ${server.theme.border}` : '1px solid transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s ease', boxShadow: isActive ? '0 2px 4px rgba(0,0,0,0.02)' : 'none' }} title={server.tooltip} onMouseEnter={(e) => { if (!isActive) e.currentTarget.style.background = '#f8fafc'; }} onMouseLeave={(e) => { if (!isActive) e.currentTarget.style.background = '#ffffff'; }}>{server.icon}</button>
          );
        })}
        <div style={{ width: '32px', height: '1px', background: '#e2e8f0', margin: '8px 0' }}></div>
        <button onClick={() => setIsModalOpen(true)} style={{ width: '42px', height: '42px', borderRadius: '10px', background: '#ffffff', color: '#64748b', fontSize: '20px', fontWeight: 300, border: '1px dashed #cbd5e1', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>+</button>
      </div>

      {/* Dynamic Sidebar */}
      <aside className="sidebar" style={{ display: 'flex', flexDirection: 'column', height: '100vh', background: '#f8fafc', borderRight: '1px solid #e2e8f0', width: '280px', flexShrink: 0 }}>
        {(() => {
          const activeServer = servers.find(s => s.id === activeServerId);
          const isGlobal = activeServerId === 'GLOBAL';
          return (
            <div style={{ padding: '24px 20px', borderBottom: '1px solid #e2e8f0', background: isGlobal ? '#ffffff' : activeServer?.theme.bg || '#ffffff', transition: 'background 0.3s' }}>
              <h2 style={{ fontSize: '16px', fontWeight: 700, margin: 0, color: isGlobal ? '#0f172a' : activeServer?.theme.text || '#0f172a', transition: 'color 0.3s' }}>
                {activeServer?.tooltip || 'OS Command Center'}
              </h2>
            </div>
          );
        })()}
        <nav style={{ padding: '20px 16px', flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {navGroups.map(group => (
            <div key={group.id} style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '12px', overflow: 'hidden', boxShadow: '0 1px 3px rgba(0,0,0,0.02)' }}>
              <button onClick={() => toggleSection(group.id)} style={{ width: '100%', padding: '12px 16px', background: openSections[group.id] ? '#f1f5f9' : '#ffffff', border: 'none', borderBottom: openSections[group.id] ? '1px solid #e2e8f0' : 'none', display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer' }}>
                <span style={{ fontSize: '13px', fontWeight: 600, color: '#334155', display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ fontSize: '16px' }}>{group.icon}</span> {group.title}</span>
                <span style={{ fontSize: '10px', color: '#94a3b8', transform: openSections[group.id] ? 'rotate(180deg)' : 'rotate(0deg)' }}>▼</span>
              </button>
              {openSections[group.id] && (
                <div style={{ padding: '8px', display: 'flex', flexDirection: 'column', gap: '2px' }}>
                  {group.links.map(link => {
                    const isActive = activeTabHref === link.href;
                    return (
                      <a key={link.href} href={link.href} onClick={(e) => handleSidebarClick(e, link.href, link.label)} style={{ textDecoration: 'none', color: isActive ? '#0f172a' : '#64748b', background: isActive ? '#f1f5f9' : 'transparent', padding: '8px 12px', borderRadius: '6px', display: 'block', fontSize: '13px', fontWeight: isActive ? 600 : 500 }}>
                        {link.label}
                      </a>
                    );
                  })}
                </div>
              )}
            </div>
          ))}
        </nav>
      </aside>

      {/* Main Content Area (Tabs + Artifact Canvas) */}
      <main className="main-content" style={{ flex: 1, display: 'flex', flexDirection: 'column', height: '100vh', overflow: 'hidden', background: '#ffffff' }}>
        
        {/* Global Tab Bar */}
        <div style={{ display: 'flex', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', padding: '8px 8px 0 8px', gap: '4px', overflowX: 'auto', flexShrink: 0 }}>
          {tabs.map(tab => (
            <div 
              key={tab.id}
              onClick={() => {
                setActiveTabHref(tab.href);
                if (tab.href.startsWith('#wiki') || tab.href.startsWith('#adobe')) {
                  setArtifactMode('IFRAME');
                } else if (tab.href.startsWith('#artifact')) {
                  setArtifactMode('SANDBOX');
                } else {
                  setArtifactMode('PAGE');
                  router.push(tab.href);
                }
              }}
              style={{ 
                padding: '8px 16px', 
                background: activeTabHref === tab.href ? '#ffffff' : 'transparent',
                color: activeTabHref === tab.href ? '#0f172a' : '#64748b',
                borderTopLeftRadius: '8px',
                borderTopRightRadius: '8px',
                border: '1px solid',
                borderColor: activeTabHref === tab.href ? '#e2e8f0 #e2e8f0 transparent #e2e8f0' : 'transparent',
                borderBottom: activeTabHref === tab.href ? '1px solid #ffffff' : 'none',
                marginBottom: activeTabHref === tab.href ? '-1px' : '0',
                fontSize: '13px',
                fontWeight: activeTabHref === tab.href ? 600 : 500,
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                whiteSpace: 'nowrap',
                transition: 'background 0.2s'
              }}
              onMouseEnter={(e) => { if (activeTabHref !== tab.href) e.currentTarget.style.background = '#f1f5f9'; }}
              onMouseLeave={(e) => { if (activeTabHref !== tab.href) e.currentTarget.style.background = 'transparent'; }}
            >
              {tab.label}
              <button 
                onClick={(e) => closeTab(e, tab.href)}
                style={{ background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '2px', borderRadius: '4px' }}
                onMouseEnter={(e) => e.currentTarget.style.background = '#e2e8f0'}
                onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
              >
                ×
              </button>
            </div>
          ))}
        </div>

        {/* Artifact Canvas Rendering Area */}
        <div style={{ flex: 1, display: 'flex', overflow: 'hidden', background: '#f8fafc' }}>
          
          <div className="page-content" style={{ flex: 1, overflowY: 'auto', padding: '0', display: 'flex', flexDirection: 'column' }}>
            
            {artifactMode === 'PAGE' && (
              <div style={{ padding: '32px 48px', flex: 1 }}>
                {activeServerId === 'GLOBAL' ? children : (
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', flexDirection: 'column', color: '#64748b' }}>
                    <div style={{ fontSize: '48px', marginBottom: '16px' }}>🚧</div>
                    <h2 style={{ color: '#0f172a' }}>Isolated Project Context</h2>
                    <p>You have entered the {servers.find(s => s.id === activeServerId)?.tooltip}.</p>
                  </div>
                )}
              </div>
            )}

            {artifactMode === 'SANDBOX' && (
              <div style={{ flex: 1, padding: '24px', display: 'flex', flexDirection: 'column' }}>
                <div style={{ marginBottom: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ background: '#dcfce7', color: '#166534', padding: '4px 8px', borderRadius: '4px', fontSize: '11px', fontWeight: 'bold' }}>LIVE ARTIFACT</span>
                    <span style={{ fontSize: '13px', color: '#64748b' }}>Generated securely via Sandpack</span>
                  </div>
                  <button className="btn">Deploy to Project</button>
                </div>
                
                <div style={{ flex: 1, borderRadius: '12px', overflow: 'hidden', border: '1px solid #e2e8f0', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}>
                  <Sandpack 
                    template="react" 
                    theme="light"
                    files={{ "/App.js": MOCK_GENERATED_CODE }} 
                    options={{ 
                      showNavigator: false, 
                      showTabs: false,
                      editorHeight: '100%',
                      editorWidthPercentage: 0,
                    }}
                  />
                </div>
              </div>
            )}

            {artifactMode === 'IFRAME' && (
              <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', background: '#f8fafc', color: '#64748b' }}>
                 {activeTabHref === '#wiki-global' && (
                   <div style={{ textAlign: 'center' }}>
                     <div style={{ fontSize: '48px', marginBottom: '16px' }}>📚</div>
                     <h2 style={{ color: '#0f172a' }}>Global Wiki Access</h2>
                     <p>IFRAME tool integration placeholder.</p>
                   </div>
                 )}
                 {activeTabHref === '#adobe-bg' && (
                   <div style={{ textAlign: 'center' }}>
                     <div style={{ fontSize: '48px', marginBottom: '16px' }}>🎨</div>
                     <h2 style={{ color: '#0f172a' }}>Adobe Background Remover</h2>
                     <p>IFRAME tool integration placeholder.</p>
                   </div>
                 )}
                 {!['#wiki-global', '#adobe-bg'].includes(activeTabHref) && (
                   <div style={{ textAlign: 'center' }}>
                     <div style={{ fontSize: '48px', marginBottom: '16px' }}>⚙️</div>
                     <h2 style={{ color: '#0f172a' }}>External Tool Loaded</h2>
                   </div>
                 )}
              </div>
            )}

          </div>

          {/* Persistent Omni-Agent Right Pane (Slide-Out) */}
          {activePane !== 'NONE' && (
            <div style={{ width: '380px', background: '#f8fafc', borderLeft: '1px solid #e2e8f0', display: 'flex', flexDirection: 'column', flexShrink: 0, boxShadow: '-4px 0 16px rgba(0,0,0,0.02)' }}>
              {activePane === 'AMY' && (
                <>
                  <div style={{ padding: '20px', borderBottom: '1px solid #e2e8f0', background: '#ffffff', display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{ width: '40px', height: '40px', borderRadius: '50%', background: '#ecfdf5', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#059669', overflow: 'hidden' }}><img src={amyAvatar} alt="Amy" style={{ width: '100%', height: '100%' }} /></div>
                    <div><h3 style={{ margin: 0, fontSize: '15px', color: '#0f172a' }}>Amy (Companion)</h3><p style={{ margin: 0, fontSize: '12px', color: '#059669', display: 'flex', alignItems: 'center', gap: '4px' }}><span style={{ width: '6px', height: '6px', background: '#059669', borderRadius: '50%', display: 'inline-block' }}></span> Omniscient Mode</p></div>
                  </div>
                  <div style={{ flex: 1, padding: '20px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '16px' }}>
                    
                    <div style={{ background: '#ffffff', padding: '16px', borderRadius: '12px', border: '1px solid #e2e8f0', fontSize: '13px', color: '#334155', boxShadow: '0 1px 3px rgba(0,0,0,0.02)' }}>
                      Hello! I can see you currently have the <strong>{tabs.find(t => t.href === activeTabHref)?.label}</strong> tab open in the <strong>{servers.find(s => s.id === activeServerId)?.tooltip || 'Global OS'}</strong> context.<br/><br/>Try asking me to <strong>&quot;build a dashboard&quot;</strong>.
                    </div>

                    {artifactMode === 'SANDBOX' && (
                      <div style={{ background: '#ecfdf5', padding: '16px', borderRadius: '12px', border: '1px solid #a7f3d0', fontSize: '13px', color: '#065f46', boxShadow: '0 1px 3px rgba(0,0,0,0.02)' }}>
                        <strong>Artifact Generated!</strong><br/>I have deployed the MRR Dashboard to your Canvas using Sandpack. You can interact with it on the left.
                      </div>
                    )}

                  </div>
                </>
              )}
              {activePane === 'KAI' && (
                <>
                  <div style={{ padding: '20px', borderBottom: '1px solid #e2e8f0', background: '#ffffff', display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{ width: '40px', height: '40px', borderRadius: '50%', background: '#eff6ff', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#2563eb', overflow: 'hidden' }}><img src={kaiAvatar} alt="Kai" style={{ width: '100%', height: '100%' }} /></div>
                    <div><h3 style={{ margin: 0, fontSize: '15px', color: '#0f172a' }}>Kai (Operations)</h3><p style={{ margin: 0, fontSize: '12px', color: '#2563eb', display: 'flex', alignItems: 'center', gap: '4px' }}><span style={{ width: '6px', height: '6px', background: '#2563eb', borderRadius: '50%', display: 'inline-block' }}></span> Multica Linked</p></div>
                  </div>
                  <div style={{ flex: 1, padding: '20px', overflowY: 'auto' }} />
                </>
              )}
              
              <div style={{ padding: '16px', background: '#ffffff', borderTop: '1px solid #e2e8f0' }}>
                <input 
                  type="text" 
                  value={amyChatInput}
                  onChange={e => setAmyChatInput(e.target.value)}
                  onKeyDown={handleAmySubmit}
                  placeholder={`Message ${activePane === 'AMY' ? 'Amy' : 'Kai'}...`} 
                  style={{ width: '100%', padding: '12px 16px', borderRadius: '24px', border: '1px solid #cbd5e1', outline: 'none', fontSize: '13px' }} 
                />
              </div>

            </div>
          )}
        </div>
      </main>

      {/* Far-Right Omni-Bar */}
      <div style={{ width: '68px', background: '#ffffff', borderLeft: '1px solid #e2e8f0', display: 'flex', flexDirection: 'column', alignItems: 'center', paddingTop: '24px', paddingBottom: '24px', zIndex: 20, boxShadow: '-2px 0 8px rgba(0,0,0,0.02)', flexShrink: 0 }}>
        
        {/* Slide-out Agents */}
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px' }}>
          <div style={{ fontSize: '10px', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Agents</div>
          
          <button onClick={() => setActivePane(activePane === 'AMY' ? 'NONE' : 'AMY')} style={{ width: '46px', height: '46px', borderRadius: '50%', background: activePane === 'AMY' ? 'linear-gradient(135deg, #10b981, #059669)' : '#ecfdf5', color: activePane === 'AMY' ? '#ffffff' : '#059669', border: activePane === 'AMY' ? 'none' : '2px solid #a7f3d0', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s ease', boxShadow: activePane === 'AMY' ? '0 0 15px rgba(16, 185, 129, 0.5)' : 'none', overflow: 'hidden', padding: 0 }} title="Amy (Companion)">
            <img src={amyAvatar} alt="Amy" style={{ width: '100%', height: '100%', opacity: activePane === 'AMY' ? 1 : 0.8 }} />
          </button>
          
          <button onClick={() => setActivePane(activePane === 'KAI' ? 'NONE' : 'KAI')} style={{ width: '46px', height: '46px', borderRadius: '50%', background: activePane === 'KAI' ? 'linear-gradient(135deg, #3b82f6, #2563eb)' : '#eff6ff', color: activePane === 'KAI' ? '#ffffff' : '#2563eb', border: activePane === 'KAI' ? 'none' : '2px solid #bfdbfe', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s ease', boxShadow: activePane === 'KAI' ? '0 0 15px rgba(59, 130, 246, 0.5)' : 'none', overflow: 'hidden', padding: 0 }} title="Kai (Operations)">
            <img src={kaiAvatar} alt="Kai" style={{ width: '100%', height: '100%', opacity: activePane === 'KAI' ? 1 : 0.8 }} />
          </button>
        </div>

        <div style={{ flex: 1 }}></div>

        {/* Global Pinned App Tabs & Tools */}
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px' }}>
          <div style={{ fontSize: '10px', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Tools</div>
          
          <button onClick={() => {
            const href = '#wiki-global';
            if (!tabs.find(t => t.href === href)) setTabs([...tabs, { id: `tab-${Date.now()}`, label: '📚 Global Wiki', href }]);
            setActiveTabHref(href);
            setArtifactMode('IFRAME');
          }} style={{ width: '42px', height: '42px', borderRadius: '10px', background: '#ffffff', color: '#64748b', border: '1px solid #e2e8f0', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s ease' }} title="Global Wiki" onMouseEnter={(e) => { e.currentTarget.style.background = '#f8fafc'; }} onMouseLeave={(e) => { e.currentTarget.style.background = '#ffffff'; }}>
            <BookOpen size={20} />
          </button>

          <button onClick={(e) => handleSidebarClick(e as any, '/tasks', 'Task Operations')} style={{ width: '42px', height: '42px', borderRadius: '10px', background: '#ffffff', color: '#64748b', border: '1px solid #e2e8f0', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s ease' }} title="Tasks" onMouseEnter={(e) => { e.currentTarget.style.background = '#f8fafc'; }} onMouseLeave={(e) => { e.currentTarget.style.background = '#ffffff'; }}>
            <CheckSquare size={20} />
          </button>

          <button onClick={(e) => handleSidebarClick(e as any, '/Global Search', 'Global Search')} style={{ width: '42px', height: '42px', borderRadius: '10px', background: '#ffffff', color: '#64748b', border: '1px solid #e2e8f0', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s ease' }} title="Global Search" onMouseEnter={(e) => { e.currentTarget.style.background = '#f8fafc'; }} onMouseLeave={(e) => { e.currentTarget.style.background = '#ffffff'; }}>
            <Search size={20} />
          </button>

          <button onClick={(e) => handleSidebarClick(e as any, '/research', 'Research')} style={{ width: '42px', height: '42px', borderRadius: '10px', background: '#ffffff', color: '#64748b', border: '1px solid #e2e8f0', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s ease' }} title="Research" onMouseEnter={(e) => { e.currentTarget.style.background = '#f8fafc'; }} onMouseLeave={(e) => { e.currentTarget.style.background = '#ffffff'; }}>
            <FlaskConical size={20} />
          </button>

          <button onClick={(e) => handleSidebarClick(e as any, '/chat', 'Co-Work Chat')} style={{ width: '42px', height: '42px', borderRadius: '10px', background: '#ffffff', color: '#64748b', border: '1px solid #e2e8f0', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s ease' }} title="Co-Work Chat" onMouseEnter={(e) => { e.currentTarget.style.background = '#f8fafc'; }} onMouseLeave={(e) => { e.currentTarget.style.background = '#ffffff'; }}>
            <MessageSquare size={20} />
          </button>

          <button onClick={(e) => handleSidebarClick(e as any, '/skills', 'Skill Library')} style={{ width: '42px', height: '42px', borderRadius: '10px', background: '#ffffff', color: '#64748b', border: '1px solid #e2e8f0', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.15s ease' }} title="Global Skill Library" onMouseEnter={(e) => { e.currentTarget.style.background = '#f8fafc'; }} onMouseLeave={(e) => { e.currentTarget.style.background = '#ffffff'; }}>
            <Library size={20} />
          </button>

          <button style={{ width: '42px', height: '42px', borderRadius: '10px', background: '#ffffff', color: '#64748b', border: '1px dashed #cbd5e1', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }} title="Pin new tool">
            <Plus size={20} />
          </button>
        </div>

      </div>
    </div>
  );
}
